[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chongming-config",
    "chongming-jwt",
    "chongming-logging",
    "chongming-worker",
    "nats-py>=2.14.0",
    "tomli>=2.4.1",
    "pydantic>=2.0.0",
]

[[tool.uv.index]]
url = "https://mirrors.ustc.edu.cn/pypi/web/simple/"

[tool.uv.sources]
chongming-config = { path = "../../utils/python/config" }
chongming-jwt = { path = "../../utils/python/jwt" }
chongming-logging = { path = "../../utils/python/logging" }
chongming-worker = { path = "../../utils/python/worker" }
