port: 4222
http: 8222
server_name: nats-2
jetstream {
    store_dir: "/data/jetstream"
    max_mem_store: 1GB
    max_file_store: 10GB
}
mqtt {
    port: 1883
}
cluster {
    name: nats-cluster
    listen: 0.0.0.0:6222
    routes = [
        "nats://nats-1:6222",
        "nats://nats-3:6222"
    ]
}
